# Numpy = Numerical Python

- Numpy배열은 n-array을 형성해서 모양을 구성
- 인덱싱, 슬라이싱, 브로드캐스팅으로 빠르게 데이터 연산하여 처리
- 배열 통계(합, 평균, 표준편차), 축(axis)
- Numpy는 배열 연산 기능을 지원한 특화된 라이브러리
- tensorflow와 조화가 좋음
- 생성할 때 크기가 결정

- 라이브러리 import 하는 방식
 - import 라이브러리명 as 별칭(라이브러리를 호칭하는 별칭 또는 약칭)
 - from ~~~.~~~~ import 라이브러리명
 - ex) import numpy as np, import pandas as pd


In [1]:
import numpy as np

In [14]:
list = [1, 2, 3]
arry = np.array(list)

arry

array([1, 2, 3])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [10]:
np.random.rand()

0.22488774996722127

In [11]:
np.random.rand(2,3)

array([[0.68076344, 0.51352996, 0.57118417],
       [0.17007378, 0.61651729, 0.39408479]])

- random 모듈의 주요 함수
 - 1) rand : 균등분포에서의 랜덤 추출
 - 2) raidint : 주어진 범위안에서 랜덤 추출
 - 3) rand : 표준정규분포에서 랜덤 추출
             -> 표준정규분포 : 평균 :0 표준편차 1
 - 4) normal : 정규분포에서 랜덤 추출
 - 5) seed : 랜덤값 생성기에서 시드를 생성
 - 6) shuffle : 리스트나 배열의 순서를 섞음

In [12]:
arry2 = np.arange(16)
arry2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
arry2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
arry2.shape

(16,)

In [16]:
arry2.dtype

dtype('int64')

In [17]:
arry3 = arry2.astype(float)
arry3

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [18]:
arry3.dtype

dtype('float64')

In [19]:
import numpy as np
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
arr[5]

np.int64(5)

In [21]:
print(arr[-1])

15


In [23]:
print(arr[5:8])

[5 6 7]


In [24]:
arr[5] = 100
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [25]:
arr[6:8] = 200, 201
arr

array([  0,   1,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

In [26]:
arr2 = np.arange(16).reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
arr2[1,1]

np.int64(5)

In [29]:
arr2[1]

array([4, 5, 6, 7])

In [30]:
arr2[0:2, 2:4]

array([[2, 3],
       [6, 7]])

In [37]:
print(arr2[:2,2:])

[[2 3]
 [6 7]]


In [38]:
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
scores_arr = np.array(scores)
scores_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [39]:
scores_arr >= 90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [40]:
scores_arr[scores_arr >= 90]

array([90, 95, 90])

In [41]:
scores_arr[scores_arr >= 90] = 100

In [42]:
scores_arr

array([ 80, 100,  70,  65,  85, 100, 100,  80,  75,  80])

In [43]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [44]:
arr + 2

array([3, 4, 5, 6])

In [45]:
arr * 2

array([2, 4, 6, 8])

In [46]:
arr2 = np.arange(5,9)
arr2

array([5, 6, 7, 8])

In [47]:
arr + arr2

array([ 6,  8, 10, 12])

In [48]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [49]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [50]:
np.add(arr,arr2)

array([ 6,  8, 10, 12])

In [51]:
np.sum(arr)

np.int64(10)

In [52]:
np.cumsum(arr)

array([ 1,  3,  6, 10])

In [53]:
np.mean(arr)

np.float64(2.5)

In [54]:
np.var(arr)

np.float64(1.25)

In [55]:
np.std(arr)

np.float64(1.118033988749895)

In [56]:
np.min(arr)

np.int64(1)

In [57]:
np.max(arr)

np.int64(4)

In [60]:
np.argmin(arr)

np.int64(0)

In [61]:
np.argmax(arr)

np.int64(3)

In [64]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [67]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])